get_filename_component(CUDATEMPLATES_ROOT ${CMAKE_CURRENT_LIST_FILE} PATH ABSOLUTE)
set(CUDATEMPLATES_INCLUDE_DIR ${CUDATEMPLATES_ROOT}/include)
set(CUDATEMPLATES_FOUND TRUE)
message(STATUS "Found CUDA Templates: ${CUDATEMPLATES_ROOT}")
